### ISSUE TITLE
View Synthesis

### ISSUE THREAD

**Issue by JiaXuanWang** [StanfordVL/GibsonEnv#74]
What should I do if I just want to do "View Synthesis" this section?

**Comment by fxia22** [comment]
The view synthesis part is implemented in https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/core/render/pcrender.py

You can modify this part of code and bypass the physics engine to render images directly.

**Comment by JiaXuanWang** [comment]
Thanks for your reply.
But I got an error:
`Traceback (most recent call last):
  File "gibson/core/render/pcrender.py", line 567, in <module>
    data = d[v]
  File "/slstore/xuan/GibsonEnv/gibson/data/datasets.py", line 355, in __getitem__
    normal_imgs = [self.loader(item) for item in normal_img_paths]
  File "/slstore/xuan/GibsonEnv/gibson/data/datasets.py", line 355, in <listcomp>
    normal_imgs = [self.loader(item) for item in normal_img_paths]
  File "/slstore/xuan/GibsonEnv/gibson/data/datasets.py", line 37, in default_loader
    img = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)#.convert('RGB')
cv2.error: OpenCV(4.0.0) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`
Our dataset does not have normal images, right?

**Comment by charliememory** [comment]
Does the current code support to render the panoramic view? I see the pano flag is set to false in https://github.com/StanfordVL/GibsonEnv/blob/8e9e23c2dcc44bb5442a25d12928103f05b51d8f/gibson/core/render/pcrender.py#L370
And the depth pano render code is commented out https://github.com/StanfordVL/GibsonEnv/blob/8e9e23c2dcc44bb5442a25d12928103f05b51d8f/gibson/core/channels/depth_render/render.cpp#L920

**Comment by cazhang** [comment]
@charliememory  any luck of using pano mode? I'd like to use the feature if possible.

**Comment by charliememory** [comment]
@cazhang I didn't follow the pano mode. It seems this feature was not supported at that moment. I am also interested in this feature.

**Comment by Changyangli** [comment]
I tried to use the pano mode but failed... What I am doing now is to take pictures from various views at the same location to build a skybox, and then stitch them together. Like this
![test](https://user-images.githubusercontent.com/26707688/73805897-f38c9f80-4795-11ea-83a7-03fe21163e5f.png)
