### ISSUE TITLE
Gibson-ros shaders loading cannot allocate memory

### ISSUE THREAD

**Issue by ashwinram10** [StanfordVL/GibsonEnv#93]
Hi. I am trying to get Gibson-ROS to work and am facing **two** errors running the turtlebot_navigation.launch file. I followed the Gibson-ros setup tutorial.

1. The Joint state publisher node fails due to PyQt error. I face this issue only after making the suggested change to $PYTHONPATH and $PATH.

2. Loading shaders gets stuck midway and throws a cannot allocate memory error. The system hangs after this requiring a reboot.

Please let me know how I can solve this issue. Thank you.

**Relevant System Info:**
Nvidia GPU GeForce GTX1070
Nvidia Driver 384.130
Python 2.7 virtual environment in miniconda3
CUDA 8.0 (in usr/local/cuda)
CUDA 9.0 (in py2.7 virtual environment)

**Nvidia-smi output after launching gibson-ros** 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P0    36W /  N/A |    698MiB /  8111MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1083      G   /usr/lib/xorg/Xorg                           362MiB |
|    0      1995      G   compiz                                        65MiB |
|    0      2261      G   ...quest-channel-token=3746673312280415774     7MiB |
|    0      3699      G   /usr/bin/python                              189MiB |
|    0      3708      G   /opt/ros/kinetic/lib/rviz/rviz                67MiB |
|    0      4566      G   ./depth_render                                 2MiB |
+-----------------------------------------------------------------------------+

**My paths after suggested changes**
$PATH ==> /opt/ros/kinetic/bin:/home/ashwinram/bin:/home/ashwinram/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

$PYTHONPATH ==> 
/home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages:/home/ashwinram/catkin_ws/src/sdc/GibsonEnv:/usr/lib/python2.7/dist-packages/:/home/ashwinram/catkin_ros/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages

**Note:**
Initially I also faced an nvcc error from build_cuda.sh which I solved exporting the usr/local/cuda 

### **Error Message **
```
roslaunch gibson-ros turtlebot_navigation.launch
... logging to /home/ashwinram/.ros/log/60b0bfcc-8da3-11e9-ad2c-34f39ae585cb/roslaunch-adacomp-3662.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/loader.py:409: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(text)
started roslaunch server http://adacomp:46013/

SUMMARY
========

PARAMETERS
 * /amcl/initial_cov_aa: 1.57
 * /amcl/kld_err: 0.05
 * /amcl/min_particles: 500
 * /cmd_vel_mux/yaml_cfg_file: /opt/ros/kinetic/...
 * /depthimage_to_laserscan/output_frame_id: /camera_depth_frame
 * /depthimage_to_laserscan/range_min: 0.45
 * /depthimage_to_laserscan/scan_height: 2
 * /move_base/DWAPlannerROS/acc_lim_theta: 10
 * /move_base/DWAPlannerROS/acc_lim_x: 2.0
 * /move_base/DWAPlannerROS/acc_lim_y: 0.0
 * /move_base/DWAPlannerROS/forward_point_distance: 0.325
 * /move_base/DWAPlannerROS/global_frame_id: odom
 * /move_base/DWAPlannerROS/goal_distance_bias: 24.0
 * /move_base/DWAPlannerROS/max_rot_vel: 20.0
 * /move_base/DWAPlannerROS/max_scaling_factor: 0.2
 * /move_base/DWAPlannerROS/max_trans_vel: 0.5
 * /move_base/DWAPlannerROS/max_vel_x: 0.5
 * /move_base/DWAPlannerROS/max_vel_y: 0.0
 * /move_base/DWAPlannerROS/min_rot_vel: 0.4
 * /move_base/DWAPlannerROS/min_trans_vel: 0.1
 * /move_base/DWAPlannerROS/min_vel_x: 0.0
 * /move_base/DWAPlannerROS/min_vel_y: 0.0
 * /move_base/DWAPlannerROS/occdist_scale: 0.5
 * /move_base/DWAPlannerROS/oscillation_reset_dist: 0.05
 * /move_base/DWAPlannerROS/path_distance_bias: 64.0
 * /move_base/DWAPlannerROS/publish_cost_grid_pc: True
 * /move_base/DWAPlannerROS/publish_traj_pc: True
 * /move_base/DWAPlannerROS/rot_stopped_vel: 0.4
 * /move_base/DWAPlannerROS/scaling_speed: 0.25
 * /move_base/DWAPlannerROS/sim_time: 2.0
 * /move_base/DWAPlannerROS/stop_time_buffer: 0.2
 * /move_base/DWAPlannerROS/trans_stopped_vel: 0.1
 * /move_base/DWAPlannerROS/vtheta_samples: 40
 * /move_base/DWAPlannerROS/vx_samples: 6
 * /move_base/DWAPlannerROS/vy_samples: 1
 * /move_base/DWAPlannerROS/xy_goal_tolerance: 0.15
 * /move_base/DWAPlannerROS/yaw_goal_tolerance: 0.3
 * /move_base/GlobalPlanner/allow_unknown: True
 * /move_base/GlobalPlanner/cost_factor: 3.0
 * /move_base/GlobalPlanner/default_tolerance: 0.0
 * /move_base/GlobalPlanner/lethal_cost: 253
 * /move_base/GlobalPlanner/neutral_cost: 50
 * /move_base/GlobalPlanner/old_navfn_behavior: False
 * /move_base/GlobalPlanner/planner_costmap_publish_frequency: 0.0
 * /move_base/GlobalPlanner/planner_window_x: 0.0
 * /move_base/GlobalPlanner/planner_window_y: 0.0
 * /move_base/GlobalPlanner/publish_potential: True
 * /move_base/GlobalPlanner/publish_scale: 100
 * /move_base/GlobalPlanner/use_dijkstra: True
 * /move_base/GlobalPlanner/use_grid_path: False
 * /move_base/GlobalPlanner/use_quadratic: True
 * /move_base/NavfnROS/allow_unknown: False
 * /move_base/NavfnROS/default_tolerance: 0.0
 * /move_base/NavfnROS/planner_window_x: 0.0
 * /move_base/NavfnROS/planner_window_y: 0.0
 * /move_base/NavfnROS/visualize_potential: False
 * /move_base/base_global_planner: navfn/NavfnROS
 * /move_base/base_local_planner: dwa_local_planner...
 * /move_base/controller_frequency: 5.0
 * /move_base/controller_patience: 3.0
 * /move_base/global_costmap/global_frame: map
 * /move_base/global_costmap/inflation_layer/cost_scaling_factor: 5.0
 * /move_base/global_costmap/inflation_layer/enabled: True
 * /move_base/global_costmap/inflation_layer/inflation_radius: 0.4
 * /move_base/global_costmap/map_type: voxel
 * /move_base/global_costmap/max_obstacle_height: 0.6
 * /move_base/global_costmap/obstacle_layer/combination_method: 1
 * /move_base/global_costmap/obstacle_layer/enabled: True
 * /move_base/global_costmap/obstacle_layer/mark_threshold: 0
 * /move_base/global_costmap/obstacle_layer/max_obstacle_height: 0.6
 * /move_base/global_costmap/obstacle_layer/observation_sources: scan bump
 * /move_base/global_costmap/obstacle_layer/obstacle_range: 2.5
 * /move_base/global_costmap/obstacle_layer/origin_z: 0.0
 * /move_base/global_costmap/obstacle_layer/publish_voxel_map: False
 * /move_base/global_costmap/obstacle_layer/raytrace_range: 3.0
 * /move_base/global_costmap/obstacle_layer/scan/clearing: True
 * /move_base/global_costmap/obstacle_layer/scan/data_type: LaserScan
 * /move_base/global_costmap/obstacle_layer/scan/marking: True
 * /move_base/global_costmap/obstacle_layer/scan/max_obstacle_height: 0.35
 * /move_base/global_costmap/obstacle_layer/scan/min_obstacle_height: 0.25
 * /move_base/global_costmap/obstacle_layer/scan/topic: scan
 * /move_base/global_costmap/obstacle_layer/track_unknown_space: True
 * /move_base/global_costmap/obstacle_layer/unknown_threshold: 15
 * /move_base/global_costmap/obstacle_layer/z_resolution: 0.2
 * /move_base/global_costmap/obstacle_layer/z_voxels: 2
 * /move_base/global_costmap/obstacle_layer2/combination_method: 1
 * /move_base/global_costmap/obstacle_layer2/enabled: True
 * /move_base/global_costmap/obstacle_layer2/observation_sources: points
 * /move_base/global_costmap/obstacle_layer2/origin_z: 0.0
 * /move_base/global_costmap/obstacle_layer2/points/clearing: True
 * /move_base/global_costmap/obstacle_layer2/points/data_type: PointCloud2
 * /move_base/global_costmap/obstacle_layer2/points/mark_threshold: 3
 * /move_base/global_costmap/obstacle_layer2/points/marking: True
 * /move_base/global_costmap/obstacle_layer2/points/max_obstacle_height: 0.6
 * /move_base/global_costmap/obstacle_layer2/points/min_obstacle_height: 0.15
 * /move_base/global_costmap/obstacle_layer2/points/observation_persistence: 2.0
 * /move_base/global_costmap/obstacle_layer2/points/obstacle_range: 1.9
 * /move_base/global_costmap/obstacle_layer2/points/raytrace_range: 2.0
 * /move_base/global_costmap/obstacle_layer2/points/topic: /gibson_ros/camer...
 * /move_base/global_costmap/obstacle_layer2/publish_voxel_map: True
 * /move_base/global_costmap/obstacle_layer2/unknown_threshold: 0
 * /move_base/global_costmap/obstacle_layer2/z_resolution: 0.05
 * /move_base/global_costmap/obstacle_layer2/z_voxels: 10
 * /move_base/global_costmap/plugins: [{'type': 'costma...
 * /move_base/global_costmap/publish_frequency: 0.5
 * /move_base/global_costmap/robot_base_frame: base_footprint
 * /move_base/global_costmap/robot_radius: 0.2
 * /move_base/global_costmap/static_layer/enabled: True
 * /move_base/global_costmap/static_map: True
 * /move_base/global_costmap/transform_tolerance: 0.5
 * /move_base/global_costmap/update_frequency: 1.0
 * /move_base/local_costmap/global_frame: odom
 * /move_base/local_costmap/height: 4.0
 * /move_base/local_costmap/inflation_layer/cost_scaling_factor: 5.0
 * /move_base/local_costmap/inflation_layer/enabled: True
 * /move_base/local_costmap/inflation_layer/inflation_radius: 0.4
 * /move_base/local_costmap/map_type: voxel
 * /move_base/local_costmap/max_obstacle_height: 0.6
 * /move_base/local_costmap/obstacle_layer/combination_method: 1
 * /move_base/local_costmap/obstacle_layer/enabled: True
 * /move_base/local_costmap/obstacle_layer/mark_threshold: 0
 * /move_base/local_costmap/obstacle_layer/max_obstacle_height: 0.6
 * /move_base/local_costmap/obstacle_layer/observation_sources: scan bump
 * /move_base/local_costmap/obstacle_layer/obstacle_range: 2.5
 * /move_base/local_costmap/obstacle_layer/origin_z: 0.0
 * /move_base/local_costmap/obstacle_layer/publish_voxel_map: False
 * /move_base/local_costmap/obstacle_layer/raytrace_range: 3.0
 * /move_base/local_costmap/obstacle_layer/scan/clearing: True
 * /move_base/local_costmap/obstacle_layer/scan/data_type: LaserScan
 * /move_base/local_costmap/obstacle_layer/scan/marking: True
 * /move_base/local_costmap/obstacle_layer/scan/max_obstacle_height: 0.35
 * /move_base/local_costmap/obstacle_layer/scan/min_obstacle_height: 0.25
 * /move_base/local_costmap/obstacle_layer/scan/topic: scan
 * /move_base/local_costmap/obstacle_layer/track_unknown_space: True
 * /move_base/local_costmap/obstacle_layer/unknown_threshold: 15
 * /move_base/local_costmap/obstacle_layer/z_resolution: 0.2
 * /move_base/local_costmap/obstacle_layer/z_voxels: 2
 * /move_base/local_costmap/obstacle_layer2/combination_method: 1
 * /move_base/local_costmap/obstacle_layer2/enabled: True
 * /move_base/local_costmap/obstacle_layer2/observation_sources: points
 * /move_base/local_costmap/obstacle_layer2/origin_z: 0.0
 * /move_base/local_costmap/obstacle_layer2/points/clearing: True
 * /move_base/local_costmap/obstacle_layer2/points/data_type: PointCloud2
 * /move_base/local_costmap/obstacle_layer2/points/mark_threshold: 3
 * /move_base/local_costmap/obstacle_layer2/points/marking: True
 * /move_base/local_costmap/obstacle_layer2/points/max_obstacle_height: 0.6
 * /move_base/local_costmap/obstacle_layer2/points/min_obstacle_height: 0.15
 * /move_base/local_costmap/obstacle_layer2/points/observation_persistence: 2.0
 * /move_base/local_costmap/obstacle_layer2/points/obstacle_range: 1.9
 * /move_base/local_costmap/obstacle_layer2/points/raytrace_range: 2.0
 * /move_base/local_costmap/obstacle_layer2/points/topic: /gibson_ros/camer...
 * /move_base/local_costmap/obstacle_layer2/publish_voxel_map: True
 * /move_base/local_costmap/obstacle_layer2/unknown_threshold: 0
 * /move_base/local_costmap/obstacle_layer2/z_resolution: 0.05
 * /move_base/local_costmap/obstacle_layer2/z_voxels: 10
 * /move_base/local_costmap/plugins: [{'type': 'costma...
 * /move_base/local_costmap/publish_frequency: 2.0
 * /move_base/local_costmap/resolution: 0.05
 * /move_base/local_costmap/robot_base_frame: base_footprint
 * /move_base/local_costmap/robot_radius: 0.2
 * /move_base/local_costmap/rolling_window: True
 * /move_base/local_costmap/static_layer/enabled: True
 * /move_base/local_costmap/static_map: False
 * /move_base/local_costmap/transform_tolerance: 0.5
 * /move_base/local_costmap/update_frequency: 5.0
 * /move_base/local_costmap/width: 4.0
 * /move_base/oscillation_distance: 0.2
 * /move_base/oscillation_timeout: 10.0
 * /move_base/planner_frequency: 1.0
 * /move_base/planner_patience: 5.0
 * /move_base/shutdown_costmaps: False
 * /robot/name: turtlebot
 * /robot/type: turtlebot
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 5.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /teleop_velocity_smoother/accel_lim_v: 1.0
 * /teleop_velocity_smoother/accel_lim_w: 2.0
 * /teleop_velocity_smoother/decel_factor: 1.5
 * /teleop_velocity_smoother/frequency: 20.0
 * /teleop_velocity_smoother/robot_feedback: 2
 * /teleop_velocity_smoother/speed_lim_v: 0.8
 * /teleop_velocity_smoother/speed_lim_w: 5.4
 * /turtlebot_teleop_joystick/axis_angular: 0
 * /turtlebot_teleop_joystick/axis_deadman: 10
 * /turtlebot_teleop_joystick/axis_linear: 1
 * /turtlebot_teleop_joystick/scale_angular: 1.5
 * /turtlebot_teleop_joystick/scale_linear: 0.5

NODES
  /
    amcl (amcl/amcl)
    cloudify (nodelet/nodelet)
    cmd_vel_mux (nodelet/nodelet)
    depthimage_to_laserscan (depthimage_to_laserscan/depthimage_to_laserscan)
    gibson_clock (gibson-ros/simulation_clock.py)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    joystick (joy/joy_node)
    map_server (map_server/map_server)
    mobile_base_nodelet_manager (nodelet/nodelet)
    move_base (move_base/move_base)
    record_player_manager (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
    teleop_velocity_smoother (nodelet/nodelet)
    turtlebot_gibson_sim (gibson-ros/turtlebot_rgbd.py)
    turtlebot_teleop_joystick (turtlebot_teleop/turtlebot_teleop_joy)

auto-starting new master
process[master]: started with pid [3674]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 60b0bfcc-8da3-11e9-ad2c-34f39ae585cb
process[rosout-1]: started with pid [3687]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [3690]
process[turtlebot_gibson_sim-3]: started with pid [3699]
process[gibson_clock-4]: started with pid [3706]
process[robot_state_publisher-5]: started with pid [3707]
process[rviz-6]: started with pid [3708]
process[mobile_base_nodelet_manager-7]: started with pid [3709]
process[cmd_vel_mux-8]: started with pid [3710]
process[teleop_velocity_smoother-9]: started with pid [3711]
process[turtlebot_teleop_joystick-10]: started with pid [3724]
process[joystick-11]: started with pid [3736]
process[depthimage_to_laserscan-12]: started with pid [3749]
process[map_server-13]: started with pid [3763]
[ERROR] [1560406846.707773759]: Couldn't open joystick /dev/input/js0. Will retry every second.
process[amcl-14]: started with pid [3790]
process[move_base-15]: started with pid [3821]
process[record_player_manager-16]: started with pid [3824]
process[cloudify-17]: started with pid [3825]
[ INFO] [1560406846.758081163]: Loading nodelet /cloudify of type depth_image_proc/point_cloud_xyzrgb to manager record_player_manager with the following remappings:
[ INFO] [1560406846.758140699]: /depth_registered/image_rect -> /gibson_ros/camera/depth/image
[ INFO] [1560406846.758158585]: /depth_registered/points -> /gibson_ros/camera/depth_registered/points
[ INFO] [1560406846.758171024]: /rgb/camera_info -> /gibson_ros/camera/depth/camera_info
[ INFO] [1560406846.758182770]: /rgb/image_rect_color -> /gibson_ros/camera/rgb/image
[ INFO] [1560406846.760367215]: waitForService: Service [/record_player_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1560406846.812580641]: Initializing nodelet with 8 worker threads.
[ INFO] [1560406846.826707562]: waitForService: Service [/record_player_manager/load_nodelet] is now available.
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher", line 6, in <module>
    from python_qt_binding.QtCore import pyqtSlot
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 271, in <module>
    getattr(sys, 'SELECT_QT_BINDING_ORDER', None),
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 117, in _select_qt_binding
    raise ImportError("Could not find Qt binding (looked for: %s):\n%s" % (', '.join(["'%s'" % b for b in binding_order]), '\n'.join(error_msgs)))
ImportError: Could not find Qt binding (looked for: 'pyqt', 'pyside'):
  ImportError for 'pyqt': /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages/PyQt5/../../.././libpng16.so.16)
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 150, in _load_pyqt
    _named_import('PyQt5.%s' % module_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 130, in _named_import
    module = builtins.__import__(name)
ImportError: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages/PyQt5/../../.././libpng16.so.16)

  ImportError for 'pyside': /home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages/PyQt5/../../../libQt5Core.so.5: version `Qt_5.12' not found (required by /home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages/PySide2/QtCore.so)
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 182, in _load_pyside
    _named_import('PySide2.%s' % module_name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/python_qt_binding/binding_helper.py", line 130, in _named_import
    module = builtins.__import__(name)
ImportError: /home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages/PyQt5/../../../libQt5Core.so.5: version `Qt_5.12' not found (required by /home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages/PySide2/QtCore.so)

[joint_state_publisher-2] process has died [pid 3690, exit code 1, cmd /opt/ros/kinetic/lib/joint_state_publisher/joint_state_publisher __name:=joint_state_publisher __log:=/home/ashwinram/.ros/log/60b0bfcc-8da3-11e9-ad2c-34f39ae585cb/joint_state_publisher-2.log].
log file: /home/ashwinram/.ros/log/60b0bfcc-8da3-11e9-ad2c-34f39ae585cb/joint_state_publisher-2*.log
/home/ashwinram/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
0x31b9c10 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x31b6650 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x31b7d30 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x31b4bd0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
pybullet build time: Jun 12 2019 16:43:30
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
0x36c1dd0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4d2fef0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x34c6430 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x35341b0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4d2fc40 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x36c1dd0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4e84fa0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4e92200 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4e8fb70 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4e91520 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4e91de0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
0x4e84fa0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c9f60) ): Attempt to set a screen on a child window.
/home/ashwinram/catkin_ws/src/gibson-ros/turtlebot_rgbd.yaml
/home/ashwinram/catkin_ws/src/visual_localise/GibsonEnv/gibson/envs/env_bases.py:66: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_data = yaml.load(f)
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.0 context
Direct GLX rendering context obtained
Making context current
0x31b6650 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x53c00f0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x4d2fef0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x36c1dd0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x4e92200 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x4e84fa0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x31b7d30 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x31aef90 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x31b4bd0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
0x33f3500 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x24c2b10) ): Attempt to set a screen on a child window.
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce GTX 1070/PCIe/SSE2
GL_VERSION=3.2.0 NVIDIA 384.130
GL_SHADING_LANGUAGE_VERSION=1.50 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.2.0 NVIDIA 384.130
Vendor = NVIDIA Corporation
Renderer = GeForce GTX 1070/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
Processing the data:
Total 1 scenes 0 train 1 test
Indexing
  0%|          | 0/1 [00:00<?, ?it/s]number of devices found 1
Loaded EGL 1.4 after reload.
100%|██████████| 1/1 [00:00<00:00,  3.89it/s]
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=GeForce GTX 1070/PCIe/SSE2
GL_VERSION=4.5.0 NVIDIA 384.130
GL_SHADING_LANGUAGE_VERSION=4.50 NVIDIA
finish loading shaders
  0%|          | 0/190 [00:00<?, ?it/s][ WARN] [1560406851.966093868]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.10039 timeout was 0.1.
 18%|█▊        | 34/190 [00:05<00:41,  3.79it/s][ WARN] [1560406856.992228602]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.100577 timeout was 0.1.
 38%|███▊      | 73/190 [00:10<00:14,  8.30it/s][ WARN] [1560406862.032185094]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.100944 timeout was 0.1.
 58%|█████▊    | 111/190 [00:16<00:11,  7.00it/s][ WARN] [1560406867.067859465]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.100893 timeout was 0.1.
 70%|███████   | 133/190 [00:19<00:09,  6.01it/s][ WARN] [1560406872.647831081]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.10035 timeout was 0.1.
 82%|████████▏ | 155/190 [00:25<00:12,  2.70it/s][ WARN] [1560406877.831199298]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.124187 timeout was 0.1.
 83%|████████▎ | 157/190 [00:27<00:16,  1.99it/s]Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 326, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 230, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

 87%|████████▋ | 166/190 [00:28<00:06,  3.89it/s][ WARN] [1560406883.368890123]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.139947 timeout was 0.1.
[ WARN] [1560406888.409333653]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.100874 timeout was 0.1.
```

**Comment by ashwinram10** [comment]
hi, the second issue has been solved. The reason was my swap memory was insufficient. After increasing it to around 4Gb the loading is proper.

**Comment by ashwinram10** [comment]
The first issue was also solved when I didn't include /usr/lib/python packages to $PYTHONPATH.

**Final PYTHONPATH**
``/home/ashwinram/miniconda3/envs/tf13/lib/python2.7/site-packages:/home/ashwinram/catkin_ws/src/sdc/GibsonEnv:/home/ashwinram/catkin_ros/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages``

I am closing this issue. Thank you.
